# Generated by Django 4.0.3 on 2022-10-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
