# Generated by Django 4.0.3 on 2022-10-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0007_category_alter_product_image_product_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(),
        ),
    ]
